### ISSUE TITLE
SAAO文件页 长文件名显示问题

### ISSUE THREAD

**Issue by luvletter2333** [Xuehuo/SAA-Online#5]
![image](https://user-images.githubusercontent.com/31475650/35191925-429aa5d2-fec2-11e7-83d9-03c9208c7c5f.png)
文件名显示有点尬
查找不便

**Comment by luvletter2333** [comment]
前端js模糊查询？

**Comment by tonnylyz** [comment]
增加一个“行视图”？
检索的问题还是靠后端去做好了，前端的话和Ctrl(Command)+F有什么差别呢。

**Comment by luvletter2333** [comment]
行视图应该就可以了
后端检索的话运行速度emm
